-- Add auto_generated flag to specs table
-- This allows us to track which specs were auto-drafted vs manually created

ALTER TABLE specs ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT FALSE;

-- Create index for faster queries on auto-generated specs
CREATE INDEX IF NOT EXISTS idx_specs_auto_generated ON specs(auto_generated, project_id);

-- Add comment
COMMENT ON COLUMN specs.auto_generated IS 'TRUE if spec was auto-generated by Proactive Spec Writer agent, FALSE if manually created by PM';
