/**
 * Event-Driven Architecture - Type Definitions
 * Core types for SignalsLoop's event system
 */

/**
 * Domain Event - Base structure for all events in the system
 */
export interface DomainEvent {
  id?: string;                    // Unique event ID (generated by database)
  type: string;                   // Event type (e.g., 'feedback.created')
  aggregate_type: string;         // Entity type (e.g., 'post', 'spec')
  aggregate_id: string;           // Entity ID
  payload: Record<string, any>;   // Event data
  metadata: EventMetadata;        // Event metadata
  version: number;                // Event schema version
  created_at?: Date;              // Event timestamp (set by database)
}

/**
 * Event Metadata - Contextual information for every event
 */
export interface EventMetadata {
  user_id?: string;               // User who triggered the event
  project_id: string;             // Project this event belongs to
  timestamp?: string;             // ISO timestamp
  correlation_id?: string;        // For tracing event chains
  source?: string;                // Source of the event (e.g., 'api', 'cron', 'agent')
  [key: string]: any;             // Allow additional metadata
}

/**
 * Event Types - All event types in the system
 */
export enum EventType {
  // Feedback Domain
  FEEDBACK_CREATED = 'feedback.created',
  FEEDBACK_UPDATED = 'feedback.updated',
  FEEDBACK_VOTED = 'feedback.voted',
  FEEDBACK_COMMENTED = 'feedback.commented',
  FEEDBACK_DELETED = 'feedback.deleted',

  // AI Analysis Domain
  SENTIMENT_ANALYZED = 'sentiment.analyzed',
  THEME_DETECTED = 'theme.detected',
  THEME_UPDATED = 'theme.updated',
  THEME_THRESHOLD_REACHED = 'theme.threshold_reached',
  DUPLICATE_FOUND = 'duplicate.found',
  PRIORITY_CALCULATED = 'priority.calculated',

  // Spec Domain
  SPEC_AUTO_DRAFTED = 'spec.auto_drafted',
  SPEC_APPROVED = 'spec.approved',
  SPEC_REJECTED = 'spec.rejected',
  SPEC_LINKED = 'spec.linked',
  SPEC_UPDATED = 'spec.updated',

  // Competitive Domain
  COMPETITOR_MENTIONED = 'competitor.mentioned',
  COMPETITOR_FEATURE_DETECTED = 'competitor.feature_detected',
  COMPETITIVE_THREAT_IDENTIFIED = 'competitive.threat_identified',

  // Notification Domain
  NOTIFICATION_SENT = 'notification.sent',

  // User Engagement Domain
  USER_ENGAGED = 'user.engaged',
  USER_AT_RISK = 'user.at_risk',

  // Roadmap Domain
  ROADMAP_UPDATED = 'roadmap.updated',
  ROADMAP_STALLED = 'roadmap.stalled',

  // Feature Impact Domain
  FEATURE_LAUNCHED = 'feature.launched',
  FEATURE_METRICS_COLLECTED = 'feature.metrics_collected',
  FEATURE_RETROSPECTIVE_RECORDED = 'feature.retrospective_recorded',
}

/**
 * Aggregate Types - Entity types in the system
 */
export enum AggregateType {
  POST = 'post',
  SPEC = 'spec',
  THEME = 'theme',
  SENTIMENT = 'sentiment_analysis',
  COMPETITOR = 'competitor',
  USER = 'user',
  PROJECT = 'project',
  ROADMAP = 'roadmap',
  FEATURE_IMPACT = 'feature_impact',
}

/**
 * Event Handler - Function signature for event handlers
 */
export type EventHandler = (event: DomainEvent) => Promise<void>;

/**
 * Event Subscription - Configuration for subscribing to events
 */
export interface EventSubscription {
  eventType: string;              // Event type to subscribe to
  handler: EventHandler;          // Handler function
  id?: string;                    // Subscription ID (for cleanup)
}
