/**
 * PDF Export API
 * Generates PDF from stakeholder query response
 */

import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { queryText, userRole, components, projectId } = body;

    if (!queryText || !userRole || !components) {
      return NextResponse.json(
        { error: 'Missing required fields: queryText, userRole, components' },
        { status: 400 }
      );
    }

    // Generate a simple HTML representation
    // In a real implementation, you'd use a library like puppeteer or playwright
    // to render the actual components and convert to PDF
    const html = generateHTMLReport(queryText, userRole, components, projectId);

    return NextResponse.json({
      success: true,
      html,
      message: 'PDF data generated successfully'
    });
  } catch (error) {
    console.error('[Export PDF API] Error:', error);
    return NextResponse.json(
      {
        error: 'Failed to generate PDF',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

/**
 * Generate HTML report from components
 */
function generateHTMLReport(
  queryText: string,
  userRole: string,
  components: any[],
  projectId: string
): string {
  const timestamp = new Date().toLocaleString();

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Stakeholder Intelligence Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
      line-height: 1.6;
      color: #333;
    }
    .header {
      border-bottom: 3px solid #8b5cf6;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #8b5cf6;
      margin: 0 0 10px 0;
    }
    .meta {
      color: #666;
      font-size: 14px;
    }
    .component {
      margin-bottom: 30px;
      padding: 20px;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      background: #f9fafb;
    }
    .component-title {
      font-weight: 600;
      font-size: 18px;
      margin-bottom: 15px;
      color: #1f2937;
    }
    .content {
      color: #4b5563;
    }
    .metric {
      font-size: 32px;
      font-weight: bold;
      color: #8b5cf6;
    }
    .theme-item {
      display: inline-block;
      padding: 8px 16px;
      margin: 4px;
      background: #8b5cf6;
      color: white;
      border-radius: 20px;
      font-size: 14px;
    }
    .feedback-item {
      padding: 12px;
      margin: 8px 0;
      border-left: 3px solid #8b5cf6;
      background: white;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Stakeholder Intelligence Report</h1>
    <div class="meta">
      <div><strong>Query:</strong> ${queryText}</div>
      <div><strong>Role:</strong> ${userRole}</div>
      <div><strong>Generated:</strong> ${timestamp}</div>
      <div><strong>Project ID:</strong> ${projectId}</div>
    </div>
  </div>

  ${components.map((component, index) => renderComponent(component, index)).join('\n')}

  <div class="footer">
    <p>Generated by SignalsLoop Stakeholder Intelligence</p>
    <p>This report contains AI-generated insights based on your product feedback data.</p>
  </div>
</body>
</html>
  `.trim();
}

/**
 * Render individual component as HTML
 */
function renderComponent(component: any, index: number): string {
  const { type, props } = component;

  switch (type) {
    case 'SummaryText':
      return `
        <div class="component">
          <div class="content">
            ${props.content}
          </div>
        </div>
      `;

    case 'MetricCard':
      return `
        <div class="component">
          <div class="component-title">${props.title}</div>
          <div class="metric">${props.value}</div>
          <div class="content">
            ${props.delta ? `<div>${props.delta}</div>` : ''}
            ${props.description ? `<div>${props.description}</div>` : ''}
          </div>
        </div>
      `;

    case 'SentimentChart':
      return `
        <div class="component">
          <div class="component-title">${props.title || 'Sentiment Trend'}</div>
          <div class="content">
            <p>Sentiment chart visualization (${props.timeRange})</p>
            <p><em>Chart data is best viewed in the interactive dashboard.</em></p>
          </div>
        </div>
      `;

    case 'ThemeCloud':
      return `
        <div class="component">
          <div class="component-title">${props.title || 'Top Themes'}</div>
          <div class="content">
            ${props.themes?.map((theme: any) =>
              `<span class="theme-item">${theme.name} (${theme.count})</span>`
            ).join('') || ''}
          </div>
        </div>
      `;

    case 'FeedbackList':
      return `
        <div class="component">
          <div class="component-title">${props.title || 'Feedback'}</div>
          <div class="content">
            ${props.items?.map((item: any) => `
              <div class="feedback-item">
                <strong>${item.title}</strong>
                ${item.content ? `<div>${item.content}</div>` : ''}
                <div style="font-size: 12px; color: #9ca3af; margin-top: 4px;">
                  Sentiment: ${item.sentiment?.toFixed(2) || 'N/A'} | Source: ${item.source || 'Unknown'}
                </div>
              </div>
            `).join('') || '<p>No feedback items</p>'}
          </div>
        </div>
      `;

    case 'ActionCard':
      return `
        <div class="component" style="border-left: 4px solid ${props.severity === 'high' ? '#ef4444' : props.severity === 'medium' ? '#f59e0b' : '#3b82f6'}">
          <div class="component-title">⚡ ${props.title}</div>
          <div class="content">
            <div><strong>Action Required:</strong> ${props.action}</div>
            ${props.description ? `<div>${props.description}</div>` : ''}
            <div style="margin-top: 8px; font-size: 14px;">
              <strong>Severity:</strong> ${props.severity?.toUpperCase() || 'UNKNOWN'}
            </div>
          </div>
        </div>
      `;

    case 'CompetitorCompare':
      return `
        <div class="component">
          <div class="component-title">${props.title || 'Competitive Comparison'}</div>
          <div class="content">
            <p><strong>Competitors:</strong> ${props.competitors?.join(', ') || 'None'}</p>
            ${props.metrics?.map((metric: any) => `
              <div style="margin: 8px 0;">
                <strong>${metric.name}:</strong> ${metric.value}
              </div>
            `).join('') || ''}
          </div>
        </div>
      `;

    case 'TimelineEvents':
      return `
        <div class="component">
          <div class="component-title">${props.title || 'Timeline Events'}</div>
          <div class="content">
            ${props.events?.map((event: any) => `
              <div class="feedback-item">
                <strong>${event.title}</strong>
                ${event.description ? `<div>${event.description}</div>` : ''}
                <div style="font-size: 12px; color: #9ca3af; margin-top: 4px;">
                  ${new Date(event.date).toLocaleDateString()} | Type: ${event.type}
                </div>
              </div>
            `).join('') || '<p>No events</p>'}
          </div>
        </div>
      `;

    default:
      return `
        <div class="component">
          <div class="content">Unknown component type: ${type}</div>
        </div>
      `;
  }
}
