#!/bin/bash

# Apply Phase 1 Event Infrastructure Migration
# This script helps you apply the event infrastructure migration to Supabase

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Phase 1: Event Infrastructure Migration                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This migration creates:"
echo "  • Events table for storing domain events"
echo "  • Database triggers for automatic event publishing"
echo "  • Realtime subscriptions for live event delivery"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 INSTRUCTIONS:"
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://app.supabase.com/project/YOUR_PROJECT_ID"
echo ""
echo "2. Navigate to: SQL Editor"
echo ""
echo "3. Click: New Query"
echo ""
echo "4. Copy the migration file:"
echo "   migrations/202511222305_phase1_event_infrastructure_combined.sql"
echo ""
echo "5. Paste into the SQL Editor and click: Run"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Press Enter to view the migration file location..."
echo ""
echo "Migration file: migrations/202511222305_phase1_event_infrastructure_combined.sql"
echo ""
echo "To copy to clipboard (macOS):"
echo "  cat migrations/202511222305_phase1_event_infrastructure_combined.sql | pbcopy"
echo ""
echo "To copy to clipboard (Linux with xclip):"
echo "  cat migrations/202511222305_phase1_event_infrastructure_combined.sql | xclip -selection clipboard"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After applying the migration:"
echo ""
echo "1. Test event publishing:"
echo "   ts-node src/lib/events/test-events.ts"
echo ""
echo "2. Or create an API route to test from your browser:"
echo "   GET /api/test/events"
echo ""
echo "3. Monitor events in your database:"
echo "   SELECT * FROM events ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  Ready to build AI-native SignalsLoop! 🚀                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
